# Generated by Django 2.2 on 2020-05-16 13:10

import agc.mixins
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('agc', '0003_auto_20200516_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlassElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Наименование')),
                ('slug', models.SlugField(blank=True, help_text='Необязательно для заполнения руками', max_length=350, verbose_name='Наименование для создания ссылки')),
                ('description', models.TextField(verbose_name='Описание материала')),
            ],
            options={
                'verbose_name': 'Изображения на странице',
                'verbose_name_plural': 'Изображения на странице',
            },
            bases=(agc.mixins.SaveModelSlugMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GlassElementImage',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250, verbose_name='Наименование цвета стекла')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Файл с картинкой большого размера')),
                ('sm_image', models.ImageField(null=True, upload_to='', verbose_name='Файл с картинкой малого размера')),
                ('priority', models.IntegerField(default=1, verbose_name='Приоритет вывода картинки')),
                ('element', models.ForeignKey(help_text='В этом поле можно использовать автозаполнение', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='agc.GlassElement', verbose_name='Стекло к которому привязана картинка')),
            ],
            options={
                'verbose_name': 'Рендер изображения со стеклом',
                'verbose_name_plural': 'Рендеры изображений со стеклом',
                'ordering': ['priority'],
            },
            bases=(agc.mixins.SaveModelImageMixin, models.Model),
        ),
    ]
