# Generated by Django 2.2 on 2020-05-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agc', '0004_glasselement_glasselementimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='glass_color',
            field=models.TextField(verbose_name='Цвет стекла'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='glass_name',
            field=models.TextField(verbose_name='Наименование стекла'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='items',
            field=models.TextField(verbose_name='Элементы, которые необходимо изготовить'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='zone_name',
            field=models.TextField(verbose_name='Наименование зоны'),
        ),
    ]
