# Generated by Django 2.2 on 2020-05-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agc', '0005_auto_20200516_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='glasselementimage',
            name='color_slug',
            field=models.SlugField(blank=True, max_length=350),
        ),
    ]
